#baseurl: /tufte-jekyll
title: William Kariampuzha Website
author: William Kariampuzha
simple_search: http://google.com/search
description: By William Kariampuzha
url: "http://wzkariampuzha.github.io"
name: tufte
github_username: wzkariampuzha
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/Chicago
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
#editor: gvim
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination:
